### ISSUE TITLE
Grabber v1.0 errata 

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Grabber#1]
_From @gkasprow on [2018-03-07 12:25](https://github.com/sinara-hw/sinara/issues/524)_

- [x] reverse LED directions (Altium bug)
- [x] ground front panel

**Comment by marmeladapk** [comment]
_From @jordens on [2018-04-16 15:41](https://github.com/sinara-hw/sinara/issues/524#issuecomment-381650269)_


* [x] front panel: swap BASE and MEDIUM labels
* [x] front panel: increase cutout width to give access to the threaded holes

**Comment by sbourdeauducq** [comment]
I received new panels:
:ok: BASE and MEDIUM labels swapped
:ok: Text changed to "Camera Input"
:x: Cutouts still at the same size

**Comment by gkasprow** [comment]
@sbourdeauducq  I missed somehow these cut-outs.
Would such cut-outs be OK? 
![obraz](https://user-images.githubusercontent.com/4325054/43390256-03eed260-93ee-11e8-9090-3ffb62d7b6fa.png)

**Comment by sbourdeauducq** [comment]
Looks fine IMHO, @jordens ?

**Comment by gkasprow** [comment]
Oh, the BASE and MEDIUM text needs to be rotated to match remaining EEMs vertical text orientation

**Comment by jordens** [comment]
If there is 2.75mm clearance radius around the threaded hole center, then yes.

**Comment by gkasprow** [comment]
@jordens Yes, it is
![obraz](https://user-images.githubusercontent.com/4325054/43392954-a307ecd6-93f5-11e8-824b-9e4706725726.png)

**Comment by gkasprow** [comment]
Edit: 2.739 < 2.75

**Comment by gkasprow** [comment]
I moved the edge and it is 2.83 now.
