### ISSUE TITLE
Check panel cutout width

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Grabber#3]
... not just "height" to fit standoffs for the two screws per connector but also the "width" of the cutout. 
@gkasprow could you check the width of the connectors? The shield of the plug goes on the outside of the jack and it's wider than the cutout in v1.0 preventing insertion completely.

This photo is supposed to show that the plug doesn't fit through the panel. It's a bit hard to see but it really doesn't fit.
![image](https://user-images.githubusercontent.com/1338946/43658222-8bf997cc-9758-11e8-8837-5369bc4716f9.png)

![image](https://user-images.githubusercontent.com/1338946/43658209-82db4dc0-9758-11e8-84d5-e64fa4afb97b.png)

**Comment by jordens** [comment]
Oh and could you make sure that in the next version we ship those threaded standoffs that the camera has?

**Comment by gkasprow** [comment]
OK, they need to be added to the BOM. It looks like [this](http://pl.farnell.com/3m/3341-31/screwlock-mdr/dp/9293108) is right PN

**Comment by gkasprow** [comment]
I increased cutout width by 1mm

**Comment by jordens** [comment]
Yeah. That should be the right PN. No comment on the thread system dependence on the number of contacts (M2.5/4-40) and the standard cables having different threads than than the connectors. I.e. how did this end up being a transatlantic adapter?

**Comment by gkasprow** [comment]
Cable screws thread seem to be the same on both coasts of the ocean. 
But connectors tend to have different options,  metric and imperial threads.

**Comment by jordens** [comment]
The connector we are using is metric up to 50 contacts and then Imperial. No options.
