### ISSUE TITLE
v1.1 review

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Grabber#4]
@jordens are you happy with the v1.1 design now, or do you have any other suggestions/recommendations for improvements?

**Comment by jordens** [comment]
We should consider adding another EEM connector plus 5 more LVDS transcievers and exposing the Z datastream. Judging from past changes, the delta in price is irrelevant and the benefit of being able to support more camera link cameras would be interesting. The newer sCMOS cameras are quite a bit faster while still providing low noise that would work fine for ion readout.

**Comment by gkasprow** [comment]
We would need to make it slightly longer to fit third EEM. 
I forgotten to swap EEM0 with EEM1!

**Comment by hartytp** [comment]
Could EEM2 fit above EEM0, so they are layout is L-shaped?

**Comment by gkasprow** [comment]
I can fit them all, but have to move to the board centre to make routing easier.
![obraz](https://user-images.githubusercontent.com/4325054/44268359-8ef02480-a231-11e8-9c59-1eedcdea30b6.png)

**Comment by hartytp** [comment]
hmm...might be worth making the board a tiny bit longer to space the connectors out more. Looks like it could be a bit tight to fit in all those IDCs with that pitch.

**Comment by gkasprow** [comment]
This is max I can do with existing board size
![obraz](https://user-images.githubusercontent.com/4325054/44270540-15a80000-a238-11e8-8809-5611e0806d6c.png)

**Comment by hartytp** [comment]
That looks pretty good to me. I'm not concerned about increasing the board a cm or two if that helps routing.

**Comment by dhslichter** [comment]
Agreed that making this board slightly longer seems like a no-brainer if it enables us to have the 3 EEM connectors and not have to pack them too tightly together.  How does this compare to the spacing on Kasli, for example?  Seems similar?

**Comment by gkasprow** [comment]
@jordens please check the newest release. I added CameraLink Full support. Please verify camera and EEM connectors signal assignment (i.e. clock routing).

**Comment by gkasprow** [comment]
since no issues were addressed, closing.
