### ISSUE TITLE
front panel opening for connector

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Grabber#6]
The opening in the front panel should be made larger to enable full insertion of the cable connector. This prevents the screws from engaging.

Apparently something like a 12.8 by 39.7 mm opening is needed. Yes, this is wider than the PCB side connector.
Typical working cable is 
https://multimedia.3m.com/mws/media/500845O/3mtm-mini-d-ribbon-mdr-cable-assembly-ts2257.pdf

I haven't been able to find a cable with those clips instead of screws to lock it in place.

Alternatively and additionally maybe pushing the connectors out by 1 mm might be sufficient while not touching the panel RF shield lip on the underside.

**Comment by gkasprow** [comment]
@jordens I moved the connectors back by 1mm, I also separated them enough to fit the cutouts. 
![obraz](https://user-images.githubusercontent.com/4325054/129456621-989c498c-670b-436c-a07a-b5d9471d13a5.png)

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/129456640-fb66567f-a8b7-4299-be33-5b75ac1575ff.png)
